<template>
<section>
  <div class="sections">

    <h1 class="headings">Contact Me</h1><br>

    <!--CONTACT BUTTONS-->

    <div class="row" style="text-align: center">
      <div class='col-md-4 mb-5'>
        <i class="bi bi-geo-alt"></i><br>
        <p class="titles">Location</p>
        <p>Cape Town, South Africa  </p>
      </div>

      <div class='col-md-4 mb-5'>
        <i class="bi bi-envelope"></i><br>
        <p class="titles">Email</p>
        <p>chadlhendricks@gmail.com</p>
      </div>

      <div class='col-md-4 mb-5'>
        <i class="bi bi-phone"></i><br>
        <p class="titles">Call Me On</p>
        <p>+27 67 020 2386</p>
      </div>
    </div>



    <!-- END OF CONTACT BUTTONS-->

       <!-- <div class="contactform col-sm-6" style="font-size: 20px;"> -->

       <!-- <form action="https://formspree.io/f/xzbywdvz" method="POST"> -->



    <!-- FORM  -->
   <div class="contactform col-sm-6" style="font-size: 20px;">

        <form @submit.prevent="handleSubmit">
          
          <div class="row">
            <div class="mb-3 col-6">
              <input type="text" class="form-control" id="fullname" name="fullname" aria-describedby="emailHelp" required="" placeholder="Name*">
            </div>

            <div class="mb-3 col-6">
              <input type="email" class="form-control" id="exampleInputEmail1" name="emailaddress" aria-describedby="emailHelp" required="" placeholder="Email Address*">
            </div>
          </div><br>

          <div class="mb-3">
              <input type="textarea" class="form-control" id="subjectbox" name="subject" required="" placeholder="Subject*">
          </div><br>

           <div class="mb-3">
              <input type="textarea" class="form-control" id="messagebox" name="message" required="" placeholder="Your Message*">
          </div><br>

          <div class="mb-3 form-check" style="text-align:center">
            <button type="submit" class="btn btn-warning">Submit</button>
            <button type="reset" class="btn btn-danger">Reset</button>

          </div>
  
        </form>

    </div>
    <!-- END OF FORM -->

      </div>
</section>


</template>


<script>




</script>

<style scoped>

.titles{
  color: #fca311ff;
}

#messagebox{
  height: 100px;
}

input{
  border-radius: 25px;
  border: none;
}

.row{
  color: white;
}

.contactform.col-sm-6 {
    padding-top: 100px;
    margin: auto;
    width: 80%;
}

label {
  color: white;
}

.form-control {
  height: 45px
}


/* BUTTONS AND THINGS */

.bi{
  color: crimson;
  font-size: 35px;
  -webkit-animation: wobble-hor-bottom 0.8s both;
	        animation: wobble-hor-bottom 0.8s both;
}

.d-block{
  border-radius: 25px;
}

.w-30{
  border-radius: 50%;
  margin-bottom: 50px;
  padding-top: 50px;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-2-21 13:42:42
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation wobble-hor-bottom
 * ----------------------------------------
 */
@-webkit-keyframes wobble-hor-bottom {
  0%,
  100% {
    -webkit-transform: translateX(0%);
            transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(-6deg);
            transform: translateX(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(6deg);
            transform: translateX(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(-3.6deg);
            transform: translateX(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(2.4deg);
            transform: translateX(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(-1.2deg);
            transform: translateX(-6px) rotate(-1.2deg);
  }
}
@keyframes wobble-hor-bottom {
  0%,
  100% {
    -webkit-transform: translateX(0%);
            transform: translateX(0%);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
  }
  15% {
    -webkit-transform: translateX(-30px) rotate(-6deg);
            transform: translateX(-30px) rotate(-6deg);
  }
  30% {
    -webkit-transform: translateX(15px) rotate(6deg);
            transform: translateX(15px) rotate(6deg);
  }
  45% {
    -webkit-transform: translateX(-15px) rotate(-3.6deg);
            transform: translateX(-15px) rotate(-3.6deg);
  }
  60% {
    -webkit-transform: translateX(9px) rotate(2.4deg);
            transform: translateX(9px) rotate(2.4deg);
  }
  75% {
    -webkit-transform: translateX(-6px) rotate(-1.2deg);
            transform: translateX(-6px) rotate(-1.2deg);
  }
}


   
</style>